# Generated by Django 3.2.16 on 2022-11-07 10:52

import core.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equivalencias', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Inicio')),
                ('vencimiento', models.DateField(verbose_name='Vencimiento')),
                ('carencia', models.IntegerField(default=0, verbose_name='Carencia')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('limite', models.FloatField(verbose_name='Límite')),
                ('periodificacion', models.IntegerField(choices=[(1, 'Mensual'), (3, 'Trimestral'), (4, 'Cuatrimestral'), (6, 'Semestral'), (12, 'Anual')], default=1, verbose_name='Periodificación')),
                ('valoracion', models.IntegerField(blank=True, choices=[(0, 'Sin Valoración'), (1, 'Inviable'), (2, 'Alto Riesgo'), (3, 'Promedio'), (4, 'Bajo Riesgo'), (5, 'Seguro')], default=0, null=True, verbose_name='Valoración')),
                ('notas', models.CharField(blank=True, default='', max_length=1200, null=True, verbose_name='Notas')),
                ('digitalizada', models.BooleanField(blank=True, default=False, null=True, verbose_name='Doc Digitalizado')),
                ('minimis', models.BooleanField(blank=True, default=False, null=True, verbose_name='Minimis')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equivalencias.entidad', verbose_name='Entidad')),
                ('moneda', models.ForeignKey(default='EUR', on_delete=django.db.models.deletion.PROTECT, to='equivalencias.moneda', verbose_name='Moneda')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equivalencias.producto', verbose_name='Producto')),
            ],
            options={
                'ordering': ['entidad', 'inicio'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIF', models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(9), core.models.primera_letra], verbose_name='CIF')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre comercial')),
                ('contacto', models.CharField(max_length=50, null=True, verbose_name='Persona de contacto')),
                ('telefono', models.BigIntegerField(null=True, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('configFile', models.FilePathField(blank=True, null=True, path=pathlib.PurePosixPath('/app'), verbose_name='Lectura BSS')),
            ],
            options={
                'ordering': ['nombre', 'CIF'],
            },
        ),
        migrations.CreateModel(
            name='Extracciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Cirbe', 'CIRBE'), ('Modelo200', 'MODELO200'), ('BSS', 'BSS')], max_length=10, verbose_name='Tipo')),
                ('ruta', models.CharField(max_length=255, verbose_name='Ruta')),
                ('ruta_unmerged', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Unmerged_Excel')),
                ('fechahora', models.DateTimeField(verbose_name='Fecha')),
                ('resultado', models.CharField(choices=[('ok', 'OK'), ('ko', 'KO')], max_length=2, null=True, verbose_name='Resultado')),
            ],
        ),
        migrations.CreateModel(
            name='Extracciones_Errores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Mensaje')),
                ('traza', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('bloqueo', models.IntegerField(choices=[(1, 'Crítico'), (2, 'Interrupción'), (3, 'Potencial')], null=True, verbose_name='Bloqueo')),
                ('tabla', models.CharField(blank=True, choices=[('Documento', 'Documento'), ('Crudos', 'Crudos'), ('Contabilidad', 'Contabilidad'), ('Ratio', 'Ratio'), ('Analitica', 'Analítica'), ('Pool', 'Pool'), ('Cirbe', 'Cirbe')], max_length=50, null=True, verbose_name='Tabla')),
                ('campo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Columna')),
                ('extraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.extracciones', verbose_name='Extracción')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to=core.models.user_file_path, verbose_name='Documento')),
                ('origen', models.CharField(choices=[('Cirbe', 'CIRBE'), ('Modelo200', 'MODELO200'), ('BSS', 'BSS')], max_length=9, verbose_name='Tipo de Archivo')),
                ('fecha', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Fecha Info')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('extraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.extracciones', verbose_name='Extracción')),
            ],
            options={
                'ordering': ['empresa', 'fecha'],
                'unique_together': {('origen', 'fecha', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ratio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100, verbose_name='Concepto')),
                ('magnitud', models.FloatField(verbose_name='Magnitud')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documento', verbose_name='Documento')),
                ('extraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.extracciones', verbose_name='Extracción')),
            ],
            options={
                'ordering': ['documento', 'concepto'],
                'unique_together': {('concepto', 'documento')},
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=50, verbose_name='Cuenta')),
                ('concepto', models.CharField(max_length=250, verbose_name='Concepto')),
                ('dispuesto', models.FloatField(verbose_name='Dispuesto')),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contrato', verbose_name='Contrato')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documento', verbose_name='Documento')),
                ('extraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.extracciones', verbose_name='Extracción')),
            ],
            options={
                'ordering': ['documento', 'cuenta'],
                'unique_together': {('cuenta', 'documento')},
            },
        ),
        migrations.CreateModel(
            name='Crudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=100, verbose_name='Cuenta')),
                ('concepto', models.CharField(default='indefinido', max_length=100, verbose_name='Concepto')),
                ('magnitud', models.FloatField(verbose_name='Magnitud')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documento', verbose_name='Documento')),
                ('extraccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.extracciones', verbose_name='Extracción')),
            ],
            options={
                'ordering': ['documento', 'cuenta'],
                'unique_together': {('cuenta', 'documento')},
            },
        ),
        migrations.CreateModel(
            name='Contabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(blank=True, max_length=100, verbose_name='Concepto')),
                ('magnitud', models.FloatField(verbose_name='Magnitud')),
                ('codigo', models.CharField(max_length=10, null=True, verbose_name='Codigo')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documento', verbose_name='Documento')),
                ('extraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.extracciones', verbose_name='Extracción')),
            ],
            options={
                'ordering': ['concepto', 'documento'],
                'unique_together': {('codigo', 'concepto', 'documento')},
            },
        ),
        migrations.CreateModel(
            name='Cirbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion', models.CharField(max_length=100, null=True, verbose_name='Operación')),
                ('dispuesto', models.FloatField(verbose_name='Dispuesto')),
                ('participantes', models.IntegerField(default=0, verbose_name='#Participantes')),
                ('importes', models.FloatField(verbose_name='Importes')),
                ('demora', models.FloatField(verbose_name='Intereses Demora')),
                ('disponible', models.FloatField(verbose_name='Disponible')),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contrato', verbose_name='Contrato')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documento', verbose_name='Documento')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equivalencias.entidad', verbose_name='Entidad')),
                ('extraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.extracciones', verbose_name='Extracción')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equivalencias.moneda', verbose_name='Moneda')),
                ('natInterv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equivalencias.natinterv', verbose_name='Naturaleza Intervención')),
                ('personal', models.ManyToManyField(to='equivalencias.Personal')),
                ('plazo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equivalencias.plazo', verbose_name='Plazo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equivalencias.producto', verbose_name='Producto')),
                ('real', models.ManyToManyField(to='equivalencias.Real')),
                ('situOper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='equivalencias.situoper', verbose_name='Situación Operacional')),
                ('solCol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='equivalencias.solcol', verbose_name='Solidario/Colaborativo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equivalencias.tipo', verbose_name='Concepto')),
            ],
            options={
                'ordering': ['documento', 'entidad', 'operacion'],
                'unique_together': {('documento', 'entidad', 'operacion')},
            },
        ),
        migrations.CreateModel(
            name='Analitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=100, verbose_name='Cuenta')),
                ('magnitud', models.FloatField(verbose_name='Magnitud')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documento', verbose_name='Documento')),
                ('extraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.extracciones', verbose_name='Extracción')),
            ],
            options={
                'ordering': ['documento', 'cuenta'],
                'unique_together': {('cuenta', 'documento')},
            },
        ),
    ]
