# Generated by Django 3.2.16 on 2022-11-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['empresa', 'origen', 'fecha']},
        ),
    ]
