# Generated by Django 3.2.16 on 2022-11-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_documento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratio',
            name='unidades',
            field=models.CharField(max_length=50, null=True, verbose_name='Unidades'),
        ),
    ]
