# Generated by Django 3.2.16 on 2022-12-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ratio_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracciones',
            name='tipo',
            field=models.CharField(choices=[('Cirbe', 'CIRBE'), ('Modelo200', 'MODELO200'), ('BSS', 'BSS')], max_length=10, null=True, verbose_name='Tipo'),
        ),
    ]
