# Generated by Django 3.2.16 on 2022-11-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='Entidad')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('tipo', models.CharField(choices=[('AED', 'AED'), ('AOA', 'AOA'), ('ARS', 'ARS'), ('ATS', 'ATS'), ('AUD', 'AUD'), ('BEF', 'BEF'), ('BGN', 'BGN'), ('BRL', 'BRL'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CLP', 'CLP'), ('CNY', 'CNY'), ('COP', 'COP'), ('CYP', 'CYP'), ('CZK', 'CZK'), ('DEM', 'DEM'), ('DKK', 'DKK'), ('DZD', 'DZD'), ('EEK', 'EEK'), ('EGP', 'EGP'), ('ESB', 'ESB'), ('ESP', 'ESP'), ('EUR', 'EUR'), ('FIM', 'FIM'), ('FRF', 'FRF'), ('GBP', 'GBP'), ('GRD', 'GRD'), ('HKD', 'HKD'), ('HRK', 'HRK'), ('HUF', 'HUF'), ('IDR', 'IDR'), ('IEP', 'IEP'), ('ILS', 'ILS'), ('INR', 'INR'), ('ISK', 'ISK'), ('ITL', 'ITL'), ('JPY', 'JPY'), ('KES', 'KES'), ('KRW', 'KRW'), ('KWD', 'KWD'), ('LBP', 'LBP'), ('LTL', 'LTL'), ('LUF', 'LUF'), ('LVL', 'LVL'), ('MAD', 'MAD'), ('MTL', 'MTL'), ('MXN', 'MXN'), ('MYR', 'MYR'), ('NLG', 'NLG'), ('NOK', 'NOK'), ('NZD', 'NZD'), ('PEN', 'PEN'), ('PHP', 'PHP'), ('PKR', 'PKR'), ('PLN', 'PLN'), ('PTE', 'PTE'), ('QAR', 'QAR'), ('RON', 'RON'), ('RUB', 'RUB'), ('RUR', 'RUR'), ('SAR', 'SAR'), ('SEK', 'SEK'), ('SGD', 'SGD'), ('SIT', 'SIT'), ('SKK', 'SKK'), ('THB', 'THB'), ('TND', 'TND'), ('TRY', 'TRY'), ('USD', 'USD'), ('US2', 'US2'), ('VEB', 'VEB'), ('VEF', 'VEF'), ('XAF', 'XAF'), ('XEU', 'XEU'), ('ZAR', 'ZAR'), ('L00', 'L00')], max_length=3, primary_key=True, serialize=False, verbose_name='Moneda')),
            ],
        ),
        migrations.CreateModel(
            name='NatInterv',
            fields=[
                ('tipo', models.CharField(choices=[('T11', 'TITULAR DE RIESGO DIRECTO'), ('T12', 'TITULAR DE RIESGO DIRECTO úNICO'), ('T13', 'TITULAR DE RIESGO DIRECTO SOLIDARIO'), ('T14', 'TIT. RIESGO DIR.MANCOMUNADO NO SOLID. CON OTROS TIT.MANCOMUNADOS'), ('T15', 'TIT. RIESGO DIR.MANCOMUNADO NO SOLID. CON OTROS TIT.MANCOMUNADOS'), ('T16', 'TITULAR DE RIESGO POR SUBVENCIONAR EL PRINCIPAL'), ('T17', 'TITULAR DE RIESGO POR SUBVENCIONAR EXCLUSIVAMENTE INTERESES'), ('T19', 'GARANTE'), ('T20', 'GARANTE SOLIDARIO'), ('T21', 'GARANTE NO SOLIDARIO'), ('T22', 'COMPROMISO DE FIRMA EN EFECTOS'), ('T23', 'COMPROMISO DE FIRMA EN EFECTOS'), ('T24', 'CONTRAPARTE EN UN DERIVADO DE CRéDITO COMPRADO'), ('T25', 'ASEGURADOR O AFIANZADOR'), ('T26', 'TERCERO COMPROMETIDO A PAGAR IMP. EN OPER. ARRENDA. FINANCIERO'), ('T27', 'ENTIDAD AGENTE DEL PRÉSTAMO SINDICADO'), ('T28', 'SOCIEDAD INSTRUMENTAL TENEDORA'), ('T29', 'ENTIDAD QUE GESTIONA LA OPERACIÓN'), ('T30', 'ENTIDAD DECLARANTE QUE CONCEDE DE FORMA SOLIDARIA LA OPERACIóN'), ('T31', 'ENTIDAD EMISORA DE LOS VALORES ADQUIRIDOS TEMPORALMENTE'), ('T32', 'ENTIDAD EMISORA DE LOS VALORES PRESTADOS'), ('T69', 'ENTIDAD EMISORA DE ACTIVOS FINANCIEROS RECIBIDOS EN GARANTíA'), ('T71', 'TITULAR DE RIESGO POR SUBVENCIONAR PRINCIPAL E INTERESES')], max_length=3, primary_key=True, serialize=False, verbose_name='Naturaleza Intervención')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('G00', 'SIN GARANTÍA PERSONAL'), ('G01', 'GARANTÍA DE ADMINISTRACIONES PÚBLICAS'), ('G02', 'GARANTÍA CESCE'), ('G03', 'GAR. EMPR. PÚBL. CUYA ACTIV. PRINC. SEA ASEGURAMIENTO/AVAL DE CRÉDITO'), ('G04', 'GARANTÍA DE ENTIDAD DE CRÉDITO RESIDENTE EN ESPAÑA'), ('G05', 'GARANTÍA DE ENTIDAD DE CRÉDITO NO RESIDENTE EN ESPAÑA'), ('G06', 'GARANTÍA DE SOCIEDAD DE GARANTÍA RECÍPROCA'), ('G07', 'GARANTÍA DE OTRA ENTIDAD DECLARANTE A LA CIR'), ('G08', 'GARANTÍA DEL RESTO DE LAS PERSONAS JURÍDICAS'), ('G09', 'GARANTÍA DE HOGARES'), ('G10', 'RESTO DE GARANTÍAS PERSONALES'), ('G11', 'HIPOTECA INMOBILIARIA (PRIMERA HIPOTECA)'), ('G12', 'HIPOTECA INMOBILIARIA (RESTO DE LAS HIPOTECAS)'), ('G13', 'GARANTÍA PIGNORATICIA (ACTIVOS FINANCIEROS)'), ('G14', 'HIPOTECA NAVAL'), ('G15', 'OPERACIÓN INSCRITA EN EL REGISTRO DE VENTAS A PLAZO DE BIENES MUEBLES'), ('G16', 'GARANTÍAS REALES DISTINTAS DE LAS ANTERIORES'), ('G17', 'ARRENDAMIENTO FINANCIERO DE BIENES INMUEBLES'), ('G18', 'ARRENDAMIENTO FINANCIERO DEL RESTO DE LOS BIENES'), ('G19', 'SIN GARANTÍA REAL'), ('G20', 'HIPOTECA INMOBILIARIA'), ('G21', 'RESTO DE LAS GARANTÍAS REALES'), ('G22', 'GA. CESCE/EMPR. PÚBL. CUYA ACT. PRINC. SEA ASEGURAMIENTO/AVAL CRÉDITO'), ('G33', 'GARANTÍA DE ENTIDAD DECLARANTE A LA CIR'), ('E14', 'TOTAL'), ('E15', 'PARCIAL')], max_length=3, unique=True, verbose_name='Garantías Personales')),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Plazo',
            fields=[
                ('tipo', models.CharField(choices=[('L01', 'HASTA TRES MESES (EXCEPTO A LA VISTA)'), ('L02', 'MÁS DE TRES MESES Y HASTA SEIS MESES'), ('L03', 'MÁS DE SEIS MESES Y HASTA UN AÑO'), ('L04', 'MÁS DE UN AÑO Y HASTA DOS AÑOS'), ('L05', 'MÁS DE DOS AÑOS Y HASTA CINCO AÑOS'), ('L06', 'MÁS DE CINCO AÑOS'), ('L07', 'VENCIMIENTO INDETERMINADO'), ('L08', 'HASTA TRES MESES'), ('L09', 'MÁS DE TRES MESES Y HASTA UN AÑO'), ('L10', 'MÁS DE UN AÑO Y HASTA 5 AÑOS')], max_length=3, primary_key=True, serialize=False, verbose_name='Plazo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('tipo', models.CharField(choices=[('compras', 'FINANCIACIÓN COMPRAS'), ('ventas', 'FINANCIACIÓN VENTAS'), ('poliza', 'PÓLIZA DE CRÉDITO'), ('aval', 'AVAL'), ('documentario', 'CRÉDITOS DOCUMENTARIOS'), ('multilinea', 'MULTILÍNEA'), ('tarjeta', 'TARJETAS'), ('prestamo', 'PRÉSTAMO'), ('leasing', 'LEASING'), ('hipoteca', 'HIPOTECA INMOBILIARIA'), ('click', 'CLICK - PAGO PROVEEDORES'), ('excepcion', 'EXCEPCIÓN'), ('sin', 'SIN CLASIFICACIÓN')], max_length=30, primary_key=True, serialize=False, verbose_name='Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Real',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('G00', 'SIN GARANTÍA PERSONAL'), ('G01', 'GARANTÍA DE ADMINISTRACIONES PÚBLICAS'), ('G02', 'GARANTÍA CESCE'), ('G03', 'GAR. EMPR. PÚBL. CUYA ACTIV. PRINC. SEA ASEGURAMIENTO/AVAL DE CRÉDITO'), ('G04', 'GARANTÍA DE ENTIDAD DE CRÉDITO RESIDENTE EN ESPAÑA'), ('G05', 'GARANTÍA DE ENTIDAD DE CRÉDITO NO RESIDENTE EN ESPAÑA'), ('G06', 'GARANTÍA DE SOCIEDAD DE GARANTÍA RECÍPROCA'), ('G07', 'GARANTÍA DE OTRA ENTIDAD DECLARANTE A LA CIR'), ('G08', 'GARANTÍA DEL RESTO DE LAS PERSONAS JURÍDICAS'), ('G09', 'GARANTÍA DE HOGARES'), ('G10', 'RESTO DE GARANTÍAS PERSONALES'), ('G11', 'HIPOTECA INMOBILIARIA (PRIMERA HIPOTECA)'), ('G12', 'HIPOTECA INMOBILIARIA (RESTO DE LAS HIPOTECAS)'), ('G13', 'GARANTÍA PIGNORATICIA (ACTIVOS FINANCIEROS)'), ('G14', 'HIPOTECA NAVAL'), ('G15', 'OPERACIÓN INSCRITA EN EL REGISTRO DE VENTAS A PLAZO DE BIENES MUEBLES'), ('G16', 'GARANTÍAS REALES DISTINTAS DE LAS ANTERIORES'), ('G17', 'ARRENDAMIENTO FINANCIERO DE BIENES INMUEBLES'), ('G18', 'ARRENDAMIENTO FINANCIERO DEL RESTO DE LOS BIENES'), ('G19', 'SIN GARANTÍA REAL'), ('G20', 'HIPOTECA INMOBILIARIA'), ('G21', 'RESTO DE LAS GARANTÍAS REALES'), ('G22', 'GA. CESCE/EMPR. PÚBL. CUYA ACT. PRINC. SEA ASEGURAMIENTO/AVAL CRÉDITO'), ('G33', 'GARANTÍA DE ENTIDAD DECLARANTE A LA CIR'), ('E14', 'TOTAL'), ('E15', 'PARCIAL')], max_length=3, unique=True, verbose_name='Garantías Reales')),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='SituOper',
            fields=[
                ('tipo', models.CharField(choices=[('I15', 'OPERACIÓN DUDOSA (SIN INCUMPLIMIENTOS O CON INCUMPLIM. HASTA 90 DÍAS)'), ('I16', 'OPERACIÓN REESTRUCTURADA AL AMPARO DEL REAL DECRETO-LEY 6/2012'), ('I17', 'OPER. DE REFINANCIACIÓN, REFINANCIADA O REESTRUCT. POR OTROS MOTIVOS'), ('I18', 'OPERACIÓN INCLUIDA EN UN CONVENIO DE ACREEDORES'), ('I19', 'OTRAS SITUACIONES CON INCUMPL. ENTRE MÁS DE 90 DÍAS Y HASTA 4 AÑOS'), ('I20', 'OTRAS SITUACIONES CON INCUMPLIMIENTOS DE MÁS DE CUATRO AÑOS'), ('I21', 'OPERACIÓN EN SUSPENSO'), ('I22', 'RESTO DE LAS SITUACIONES')], max_length=3, primary_key=True, serialize=False, verbose_name='Situación Operacional')),
            ],
        ),
        migrations.CreateModel(
            name='SolCol',
            fields=[
                ('tipo', models.CharField(choices=[('T33', 'SOLIDARIO'), ('T34', 'COLECTIVO')], max_length=3, primary_key=True, serialize=False, verbose_name='Solidario/Colaborativo')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('tipo', models.CharField(choices=[('VA0', 'CRÉDITO FINANCIERO. RESTO DE LAS CUENTAS DE CORRESPONSALÍA'), ('VBD', 'CRÉDITO FINANCIERO. DERECHOS DE COBRO SOBRE TARIFAS REGULADAS'), ('VB1', 'PRÉST. RECOMPRA INVERSA. GAR. EFECTIVO ENTREG. EN PERMUTAS DE VALORES'), ('VB2', 'PRÉST. RECOMPRA INVERSA. RESTO DE LOS PRÉSTAMOS DE RECOMPRA INVERSA'), ('VB3', 'AVALES POR CANTIDADES ANTICIP. EN LA CONSTRUCCIÓN Y VENTA VIVIENDAS'), ('VB4', 'CRÉDITO FINANCIERO. DERECHOS DE COBRO POR SUBVENCIONES'), ('V19', 'VALORES PRESTADOS'), ('V24', 'CRÉDITO COMERCIAL CON RECURSO'), ('V25', 'CRÉDITO COMERCIAL CON RECURSO. DESCUENTO DE PAPEL COMERCIAL'), ('V26', 'CRÉDITO COMERCIAL CON RECURSO. RESTO DE LAS OPERACIONES'), ('V27', 'CRÉDITO COMERCIAL SIN RECURSO'), ('V28', 'CRÉDITO COMERCIAL SIN RECURSO. PAGO A PROVEEDORES CON INVERSIÓN'), ('V29', 'CRÉDITO COMERCIAL SIN RECURSO. PAGO A PROVEEDORES SIN INVERSIÓN'), ('V30', 'CRÉDITO COMERCIAL SIN RECURSO. FACTORING CON INVERSIÓN'), ('V31', 'CRÉDITO COMERCIAL SIN RECURSO. FACTORING SIN INVERSIÓN'), ('V32', 'CRÉDITO FINANCIERO'), ('V33', 'CRÉDITO FINANCIERO. CUENTAS DE CRÉDITO CON DISPOSICIONES POR ETAPAS'), ('V34', 'CRÉDITO FINANCIERO. RESTO DE LAS CUENTAS DE CRÉDITO'), ('V35', 'CRÉDITO FINANCIERO. EFECTOS FINANCIEROS'), ('V36', 'CRÉDITO FINANCIERO. PRÉSTAMOS CON DISPOSICIONES POR ETAPAS'), ('V37', 'CRÉDITO FINANCIERO. HIPOTECAS INVERSAS'), ('V38', 'CRÉDITO FINANCIERO. OTROS PRÉST. CON ENTREGAS APLAZADAS DE PRINCIPAL'), ('V39', 'CRÉDITO FINANCIERO. PRÉSTAMOS HÍBRIDOS'), ('V40', 'CRÉDITO FINANCIERO. RESTO DE LOS PRÉSTAMOS A PLAZO'), ('V41', 'CRÉDITO FINANCIERO. TARJETAS DE CRÉDITO'), ('V42', 'CRÉDITO FINANCIERO. CUENTAS CORRIENTES O DE AHORRO'), ('V43', 'CRÉDITO FINANCIERO. CUENTAS MUTUAS'), ('V44', 'CRÉDITO FINANCIERO. DESCUBIERTOS'), ('V45', 'CRÉDITO FINANCIERO. EXCEDIDOS EN CUENTAS DE CRÉDITO'), ('V46', 'CRÉDITO FINANCIERO. ANTICIPOS DE PENSIÓN O NÓMINA'), ('V47', 'CRÉDITO FINANCIERO. ACTIVOS PROCEDENTES DE OPERAC. FUERA DE BALANCE'), ('V48', 'CRÉDITO FINANCIERO. DERIVADOS IMPAGADOS'), ('V49', 'CRÉDITO FINANCIERO. RESTO DE LOS PRÉSTAMOS A LA VISTA'), ('V51', 'ARRENDAMIENTO FINANCIERO PARA EL ARRENDATARIO'), ('V52', 'ARRENDAMIENTO OPERATIVO PARA EL ARRENDATARIO'), ('V53', 'PRÉSTAMOS DE RECOMPRA INVERSA'), ('V54', 'VALORES REPRESENTATIVOS DE DEUDA'), ('V55', 'AVAL FINANCIERO'), ('V56', 'AVAL FINANCIERO ANTE ENTIDAD DECLARANTE'), ('V57', 'AVAL FINANCIERO SOLIDARIO CON OTRAS ENTIDADES DECLARANTES'), ('V58', 'RESTO DE AVALES FINANCIEROS'), ('V59', 'DERIVADO DE CRÉDITO (PROTECCIÓN VENDIDA)'), ('V60', 'DERIVADO DE CRÉDITO (PROTECCIÓN VENDIDA) ANTE ENTIDAD DECLARANTE'), ('V61', 'RESTO DE DERIVADO DE CRÉDITO (PROTECCIÓN VENDIDA)'), ('V62', 'DEPÓSITOS A FUTURO'), ('V63', 'AVALES Y CAUCIONES NO FINANCIEROS PRESTADOS'), ('V64', 'RESTO DE GARANTÍAS NO FINANCIERAS CONCEDIDAS. ANTE ENTIDAD DECLARANT'), ('V65', 'RESTO GAR. NO FINAN. CONCEDIDAS. SOLIDARIOS CON OTRAS ENTIDADES DECL.'), ('V66', 'RESTO DE GARANTÍAS NO FINANCIERAS CONCEDIDAS. RESTO'), ('V67', 'CRÉDITOS DOCUMENTARIOS IRREVOCABLES'), ('V68', 'DISPONIBLES EN OTROS COMPROMISOS'), ('V69', 'DISPONIBLES EN OTROS COMPROMISOS. PÓLIZAS DE RIESGO GLOBAL MULTIUSO'), ('V70', 'DISPONIBLES EN OTROS COMPROMISOS. LÍNEA DE AVALES'), ('V71', 'DISPONIBLES EN OTROS COMPROMISOS. LÍNEA DE CRÉDITOS DOCUMENTARIOS'), ('V72', 'DISPONIBLES EN OTROS COMPROMISOS. CRÉDITO POR DISPOSICIONES')], max_length=3, primary_key=True, serialize=False, verbose_name='Tipo')),
            ],
        ),
    ]
