# Generated by Django 3.2.16 on 2022-12-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equivalencias', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='entidad',
            name='codigo',
            field=models.CharField(default=None, max_length=5, null=True, unique=True, verbose_name='Código'),
        ),
    ]
