DELETE FROM ContabilidadConfiguraciones
GO

INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'activo no corriente', 2, 'ACTIVO FIJO')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'inmovilizado intangible', 3, 'Inmaterial')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'inmovilizado material', 3, 'Material')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'inversiones inmobiliarias', 3, 'Inv. Inmobiliarias')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'inversiones en empresas del grupo y asociadas a largo plazo', 3, 'Inv. Empresas del grupo L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'inversiones financieras a largo plazo', 3, 'Inv. Financieras L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'activos por impuesto diferido', 3, 'Activos por impuestos diferidos')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'deudores comerciales no corrientes', 3, 'Deudores comerciales no corrientes')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'activo corriente', 2, 'ACTIVO CIRCULANTE')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'activos no corrientes mantenidos para la venta', 3, 'Activos no corrientes para la venta')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'existencias', 3, 'Existencias')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'deudores comerciales y otras cuentas a cobrar', 3, 'Deudores comerciales')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'clientes por ventas y prestaciones de servicios', 4, 'Clientes por ventas y prestaciones de servicios')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'accionistas socios por desembolsos exigidos', 4, 'Accionistas por desembolsos exigidos')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'otros deudores', 4, 'Otros deudores')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'inversiones en empresas del grupo y asociadas a corto plazo', 3, 'Inversiones en empresas del grupo C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'inversiones financieras a corto plazo', 3, 'Inversiones financieras C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'periodificaciones a corto plazo_activo', 3, 'Periodificaciones C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'efectivo y otros activos liquidos equivalentes', 3, 'Efectivo')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'total activo', 1, 'TOTAL ACTIVO')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'patrimonio neto', 2, 'PATRIMONIO')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'fondos propios', 3, 'Fondos Propios')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'capital', 4, 'Capital Social')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'prima de emision', 4, 'Prima de emisiÃ³n')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'reservas', 4, 'Reservas')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'acciones y participaciones en patrimonio propias', 4, 'Acciones en patrimonio propias')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'resultados de ejercicios anteriores', 4, 'Resultados de ejercicios anteriores')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'otras aportaciones de socios', 4, 'Otras aportaciones de socios')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'resultado del ejercicio', 4, 'Resultados Ejercicio')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'dividendo a cuenta', 4, 'Dividendos')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'otros instrumentos de patrimonio neto', 4, 'Otros')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'ajustes por cambios de valor', 3, 'Otros')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'subvenciones, donaciones y legados recibidos', 3, 'Subvenciones')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'pasivo no corriente', 2, 'PASIVO NO CORRIENTE')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'provisiones a largo plazo', 3, 'Provisiones L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'deudas a largo plazo', 3, 'Deudas L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'deudas con entidades de credito a largo plazo', 4, 'Deudas bancarias L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'acreedores por arrendamiento financiero a largo plazo', 4, 'Arrendamiento L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'otras deudas a largo plazo', 4, 'Otras deudas L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'deudas con empresas del grupo y asociadas a largo plazo', 3, 'Deudas con empresas del grupo L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'pasivos por impuesto diferido', 3, 'Pasivos por impuestos diferidos')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'periodificaciones a largo plazo', 3, 'Periodificaciones a L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'deuda con caracteristicas especiales a largo plazo', 3, 'Deuda con caractarísticas especiales a L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'acreedores comerciales no corrientes', 3, 'Acreedores comerciales')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'pasivo corriente', 2, 'PASIVO CORRIENTE')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'pasivos vinculados con activos no corrientes mantenidos para la venta', 3, 'Pasivos corrientes para su venta')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'provisiones a corto plazo', 3, 'Provisiones a C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'deudas a corto plazo', 3, 'Deudas C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'deudas con entidades de credito a corto plazo', 4, 'Deudas bancarias a C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'acreedores por arrendamiento financiero a corto plazo', 4, 'Arrendamiento C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'otras deudas a corto plazo', 4, 'Otras deudas C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'deudas con empresas del grupo y asociadas a corto plazo', 3, 'Deudas con empresas del grupo a C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'acreedores comerciales y otras cuentas a pagar', 3, 'Acreedores y cuentas a pagar')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'periodificaciones a corto plazo_pasivo', 3, 'Periodificaciones a C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'deuda con caracteristicas especiales a corto plazo',3, 'Deudas con características especiales C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'total patrimonio neto y pasivo', 1, 'TOTAL PASIVO')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'importe neto de la cifra de negocios', 2, 'Ventas')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'variacion de existencias de productos terminados y en curso de fabricacion', 3, 'Variación de existencias')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'trabajos realizados por la empresa para su activo', 3, 'Trabajos realizados para su activo')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'aprovisionamientos', 3, 'Aprovisionamientos')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'otros ingresos de explotacion', 3, 'Otros ingresos de explotación')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'gastos de personal', 3, 'Gastos de personal')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'otros gastos de explotacion', 3, 'Otros gastos de explotación')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'amortizacion del inmovilizado', 3, 'Amortización')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'imputacion de subvenciones de inmovilizado no financiero y otras', 3, 'Imputación de subvenciones de inmovilizado no financiero')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'excesos de provisiones', 3, 'Exceso de provisiones')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'deterioro y resultado por enajenaciones del inmovilizado', 3, 'Deterioro y resultado por enajenación del inmovilizado')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'diferencia negativa de combinaciones de negocio', 3, 'Diferencia negativa de combinacies de negocio')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'otros resultados', 3, 'Otros resultados')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'resultado de explotacion', 2, 'Resultado de explotación BAII')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'ingresos financieros', 3, 'Ingresos financieros')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'gastos financieros', 3, 'Gastos financieros')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'variacion de valor razonable en instrumentos financieros', 3, 'Variación de valor de instrumentos financieros')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'diferencias de cambio', 3, 'Diferencias de cambio')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'deterioro y resultado por enajenaciones de instrumentos financieros', 3, 'Deterioro y resultado por enajenaciones')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'otros ingresos y gastos de caracter financiero', 3, 'Otros resultados de caracter financiero')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'resultado financiero', 2, 'Resultado financiero')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'resultado antes de impuestos', 2, 'Resultado antes de impuestos BAI')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'impuestos sobre beneficios', 3, 'Impuestos')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'resultado del ejercicio procedente de operaciones continuadas', 1, 'Resultado del ejercicio')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'costes fijos', 2, 'Costes fijos')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'margen de contribucion', 2, 'Margen de contribución')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'ebitda', 2, 'EBITDA')
GO
