INSERT INTO Interpretaciones VALUES ('activo corriente/BAI','Activo Corriente/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('activo corriente/BAII','Activo Corriente/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('activo corriente/BN','Activo Corriente/BN','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('activo corriente/cashflow','Activo Corriente/Cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('activo corriente/EBITDA','Activo Corriente/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('activo corriente/ventas','Activo Corriente/Ventas','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('activo no corriente/BAI','Activo No Corriente/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('activo no corriente/BAII','Activo No Corriente/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('activo no corriente/BN','Activo No Corriente/BN','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('activo no corriente/cashflow','Activo No Corriente/Cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('activo no corriente/EBITDA','Activo No Corriente/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('activo no corriente/ventas','Activo No Corriente/Ventas','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('activo/BAI','Activo/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('activo/BAII','Activo/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('activo/BN','Activo/BN','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('activo/cashflow','Activo/Cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('activo/EBITDA','Activo/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('activo/venta','Activo/Venta','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('apalancamiento financiero','Apalancamiento Financiero','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAI','BAI','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAI/activo','BAI/activo','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAI/activo corriente','BAI/activo corriente','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAI/activo no corriente','BAI/activo no corriente','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAI/capital','BAI/capital','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAI/DFB','BAI/DFB','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAI/DFB C/P','BAI/DFB C/P','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAI/DFB L/P','BAI/DFB L/P','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAI/FFPP','BAI/FFPP','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAI/ventas','BAI/ventas','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAII','BAII','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAII/activo','BAII/activo','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAII/activo corriente','BAII/activo corriente','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAII/activo no corriente','BAII/activo no corriente','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAII/capital','BAII/capital','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAII/DFB','BAII/DFB','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAII/DFB C/P','BAII/DFB C/P','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAII/DFB L/P','BAII/DFB L/P','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAII/FFPP','BAII/FFPP','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BAII/ventas','BAII/ventas','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BN','BN','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BN/(FFPP-beneficio año,1)','BN/(FFPP-beneficio año,1)','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BN/activo','BN/activo','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BN/activo corriente','BN/activo corriente','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BN/activo no corriente','BN/activo no corriente','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BN/capital','BN/capital','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BN/DFB','BN/DFB','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BN/DFB C/P','BN/DFB C/P','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BN/DFB L/P','BN/DFB L/P','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BN/FFPP','BN/FFPP','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('BN/ventas','BN/ventas','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('calidad deuda','Calidad Deuda','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('capital/BAI','Capital/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('capital/BAII','Capital/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('capital/BN','Capital/BN','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('capital/cashflow','Capital/cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('capital/EBITDA','Capital/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('capital/ventas','Capital/Ventas','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('cashflow','Cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('cashflow/activo','cashflow/activo','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('cashflow/activo corriente','cashflow/activo corriente','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('cashflow/activo no corriente','cashflow/activo no corriente','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('cashflow/capital','cashflow/capital','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('cashflow/DFB','cashflow/DFB','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('cashflow/DFB C/P','cashflow/DFB C/P','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('cashflow/DFB L/P','cashflow/DFB L/P','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('cashflow/DFN','cashflow/DFN','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('cashflow/FFPP','cashflow/FFPP','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('cashflow/ventas','Cashflow/Ventas','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('compras medias diarias','Compras Medias Diarias','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('coste de deuda','Coste de Deuda','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB','DFB','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB C/P','DFB C/P','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB C/P/BAI','DFB C/P/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB C/P/BAII','DFB C/P/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB C/P/BN','DFB C/P/BN','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB C/P/cashflow','DFB C/P/cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB C/P/EBITDA','DFB C/P/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB C/P/ventas','DFB C/P/ventas','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB L/P','DFB L/P','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB L/P/BAI','DFB L/P/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB L/P/BAII','DFB L/P/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB L/P/BN','DFB L/P/BN','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB L/P/cashflow','DFB L/P/cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB L/P/EBITDA','DFB L/P/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB L/P/ventas','DFB L/P/ventas','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB/BAI','DFB/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB/BAII','DFB/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB/BN','DFB/BN','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB/cashflow','DFB/cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB/EBITDA','DFB/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFB/ventas','DFB/ventas','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFN','DFN','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFN/cashflow','DFN/cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('DFN/EBITDA','DFN/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('disponibilidad','Disponibilidad','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('EBITDA','EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('EBITDA/activo','EBITDA/activo','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('EBITDA/activo corriente','EBITDA/activo corriente','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('EBITDA/activo no corriente','EBITDA/activo no corriente','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('EBITDA/capital','EBITDA/capital','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('EBITDA/DFB','EBITDA/DFB','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('EBITDA/DFB C/P','EBITDA/DFB C/P','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('EBITDA/DFB L/P','EBITDA/DFB L/P','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('EBITDA/FFPP','EBITDA/FFPP','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('EBITDA/ventas','EBITDA/ventas','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('endeudamiento','Endeudamiento','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('FFPP/BAI','FFPP/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('FFPP/BAII','FFPP/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('FFPP/BN','FFPP/BN','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('FFPP/cashflow','FFPP/cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('FFPP/EBITDA','FFPP/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('FFPP/ventas','FFPP/ventas','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('fondo maniobra','Fondo Maniobra','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('fondo maniobra/activo total','Fondo Maniobra/Activo Total','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('liquidez','Liquidez','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('margen de contribucion','Margen de Contribucion','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('PM Cobro','PM Cobro','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('PM Proveedores','PM Proveedores','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('prueba acida','Prueba Ácida','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('punto muerto','Punto Muerto','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('punto muerto mensual','Punto Muerto Mensual','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('ROA/ROI','ROA/ROI','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('ROE','ROE','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('ventas','Ventas','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('ventas medias diarias','Ventas Medias Diarias','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('ventas/activo','Ventas/Activo','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('ventas/activo corriente','Ventas/Activo Corriente','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('ventas/activo no corriente','Ventas/Activo No Corriente','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('ventas/BAI','Ventas/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('ventas/BAII','Ventas/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('ventas/BN','Ventas/BN','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('ventas/capital','Ventas/Capital','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('ventas/cashflow','Ventas/Cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('ventas/DFB','Ventas/DFB','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('ventas/DFB C/P','Ventas/DFB C/P','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('ventas/DFB L/P','Ventas/DFB L/P','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('ventas/EBITDA','Ventas/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('ventas/FFPP','Ventas/FFPP','verde','rojo','arriba','abajo',1)
INSERT INTO Interpretaciones VALUES ('porcentaje cobertura','% Cobertura','verde','rojo','arriba','abajo',2)
INSERT INTO Interpretaciones VALUES ('servicio deuda','Servicio de Deuda','verde','rojo','arriba','abajo',2)
