INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'provisiones a corto plazo', 3, 'Provisiones a C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'deudas a corto plazo', 3, 'Deudas C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'deudas con entidades de credito a corto plazo', 4, 'Deudas bancarias a C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'acreedores por arrendamiento financiero a corto plazo', 4, 'Arrendamiento C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'otras deudas a corto plazo', 4, 'Otras deudas C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'deudas con empresas del grupo y asociadas a corto plazo', 3, 'Deudas con empresas del grupo a C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'acreedores comerciales y otras cuentas a pagar', 3, 'Acreedores y cuentas a pagar')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'periodificaciones a corto plazo_pasivo', 3, 'Periodificaciones a C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'deuda con caracteristicas especiales a corto plazo',3, 'Deudas con características especiales C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'total patrimonio neto y pasivo', 1, 'TOTAL PASIVO')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'importe neto de la cifra de negocios', 2, 'Ventas')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'variacion de existencias de productos terminados y en curso de fabricacion', 3, 'Variación de existencias')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'trabajos realizados por la empresa para su activo', 3, 'Trabajos realizados para su activo')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'aprovisionamientos', 3, 'Aprovisionamientos')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'otros ingresos de explotacion', 3, 'Otros ingresos de explotación')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'gastos de personal', 3, 'Gastos de personal')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'otros gastos de explotacion', 3, 'Otros gastos de explotación')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'amortizacion del inmovilizado', 3, 'Amortización')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'imputacion de subvenciones de inmovilizado no financiero y otras', 3, 'Imputación de subvenciones de inmovilizado no financiero')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'excesos de provisiones', 3, 'Exceso de provisiones')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'deterioro y resultado por enajenaciones del inmovilizado', 3, 'Deterioro y resultado por enajenación del inmovilizado')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'diferencia negativa de combinaciones de negocio', 3, 'Diferencia negativa de combinacies de negocio')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'otros resultados', 3, 'Otros resultados')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'resultado de explotacion', 2, 'Resultado de explotación BAII')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'ingresos financieros', 3, 'Ingresos financieros')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'gastos financieros', 3, 'Gastos financieros')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'variacion de valor razonable en instrumentos financieros', 3, 'Variación de valor de instrumentos financieros')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'diferencias de cambio', 3, 'Diferencias de cambio')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'deterioro y resultado por enajenaciones de instrumentos financieros', 3, 'Deterioro y resultado por enajenaciones')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'otros ingresos y gastos de caracter financiero', 3, 'Otros resultados de caracter financiero')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'resultado financiero', 2, 'Resultado financiero')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'resultado antes de impuestos', 2, 'Resultado antes de impuestos BAI')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'impuestos sobre beneficios', 3, 'Impuestos')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'resultado del ejercicio procedente de operaciones continuadas', 1, 'Resultado del ejercicio')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'costes fijos', 2, 'Costes fijos')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'margen de contribucion', 2, 'Margen de contribución')
INSERT INTO ContabilidadConfiguraciones VALUES ('resultados', 'ebitda', 2, 'EBITDA')
