INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'activo no corriente', 2, 'ACTIVO FIJO')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'inmovilizado intangible', 3, 'Inmaterial')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'inmovilizado material', 3, 'Material')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'inversiones inmobiliarias', 3, 'Inv. Inmobiliarias')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'inversiones en empresas del grupo y asociadas a largo plazo', 3, 'Inv. Empresas del grupo L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'inversiones financieras a largo plazo', 3, 'Inv. Financieras L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'activos por impuesto diferido', 3, 'Activos por impuestos diferidos')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'deudores comerciales no corrientes', 3, 'Deudores comerciales no corrientes')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'activo corriente', 2, 'ACTIVO CIRCULANTE')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'activos no corrientes mantenidos para la venta', 3, 'Activos no corrientes para la venta')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'existencias', 3, 'Existencias')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'deudores comerciales y otras cuentas a cobrar', 3, 'Deudores comerciales')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'clientes por ventas y prestaciones de servicios', 4, 'Clientes por ventas y prestaciones de servicios')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'accionistas socios por desembolsos exigidos', 4, 'Accionistas por desembolsos exigidos')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'otros deudores', 4, 'Otros deudores')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'inversiones en empresas del grupo y asociadas a corto plazo', 3, 'Inversiones en empresas del grupo C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'inversiones financieras a corto plazo', 3, 'Inversiones financieras C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'periodificaciones a corto plazo_activo', 3, 'Periodificaciones C/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'efectivo y otros activos liquidos equivalentes', 3, 'Efectivo')
INSERT INTO ContabilidadConfiguraciones VALUES ('activo', 'total activo', 1, 'TOTAL ACTIVO')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'patrimonio neto', 2, 'PATRIMONIO')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'fondos propios', 3, 'Fondos Propios')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'capital', 4, 'Capital Social')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'prima de emision', 4, 'Prima de emisiÃ³n')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'reservas', 4, 'Reservas')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'acciones y participaciones en patrimonio propias', 4, 'Acciones en patrimonio propias')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'resultados de ejercicios anteriores', 4, 'Resultados de ejercicios anteriores')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'otras aportaciones de socios', 4, 'Otras aportaciones de socios')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'resultado del ejercicio', 4, 'Resultados Ejercicio')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'dividendo a cuenta', 4, 'Dividendos')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'otros instrumentos de patrimonio neto', 4, 'Otros')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'ajustes por cambios de valor', 3, 'Otros')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'subvenciones, donaciones y legados recibidos', 3, 'Subvenciones')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'pasivo no corriente', 2, 'PASIVO NO CORRIENTE')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'provisiones a largo plazo', 3, 'Provisiones L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'deudas a largo plazo', 3, 'Deudas L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'deudas con entidades de credito a largo plazo', 4, 'Deudas bancarias L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'acreedores por arrendamiento financiero a largo plazo', 4, 'Arrendamiento L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'otras deudas a largo plazo', 4, 'Otras deudas L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'deudas con empresas del grupo y asociadas a largo plazo', 3, 'Deudas con empresas del grupo L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'pasivos por impuesto diferido', 3, 'Pasivos por impuestos diferidos')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'periodificaciones a largo plazo', 3, 'Periodificaciones a L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'deuda con caracteristicas especiales a largo plazo', 3, 'Deuda con caractarísticas especiales a L/P')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'acreedores comerciales no corrientes', 3, 'Acreedores comerciales')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'pasivo corriente', 2, 'PASIVO CORRIENTE')
INSERT INTO ContabilidadConfiguraciones VALUES ('pasivo', 'pasivos vinculados con activos no corrientes mantenidos para la venta', 3, 'Pasivos corrientes para su venta')
