INSERT INTO RatioMaestros VALUES ('activo corriente/BAI','Activo Corriente/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('activo corriente/BAII','Activo Corriente/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('activo corriente/BN','Activo Corriente/BN','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('activo corriente/cashflow','Activo Corriente/Cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('activo corriente/EBITDA','Activo Corriente/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('activo corriente/ventas','Activo Corriente/Ventas','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('activo no corriente/BAI','Activo No Corriente/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('activo no corriente/BAII','Activo No Corriente/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('activo no corriente/BN','Activo No Corriente/BN','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('activo no corriente/cashflow','Activo No Corriente/Cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('activo no corriente/EBITDA','Activo No Corriente/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('activo no corriente/ventas','Activo No Corriente/Ventas','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('activo/BAI','Activo/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('activo/BAII','Activo/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('activo/BN','Activo/BN','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('activo/cashflow','Activo/Cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('activo/EBITDA','Activo/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('activo/venta','Activo/Venta','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('apalancamiento financiero','Apalancamiento Financiero','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAI','BAI','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAI/activo','BAI/activo','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAI/activo corriente','BAI/activo corriente','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAI/activo no corriente','BAI/activo no corriente','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAI/capital','BAI/capital','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAI/DFB','BAI/DFB','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAI/DFB C/P','BAI/DFB C/P','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAI/DFB L/P','BAI/DFB L/P','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAI/FFPP','BAI/FFPP','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAI/ventas','BAI/ventas','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAII','BAII','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAII/activo','BAII/activo','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAII/activo corriente','BAII/activo corriente','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAII/activo no corriente','BAII/activo no corriente','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAII/capital','BAII/capital','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAII/DFB','BAII/DFB','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAII/DFB C/P','BAII/DFB C/P','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAII/DFB L/P','BAII/DFB L/P','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAII/FFPP','BAII/FFPP','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BAII/ventas','BAII/ventas','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BN','BN','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BN/(FFPP-beneficio año,1)','BN/(FFPP-beneficio año,1)','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BN/activo','BN/activo','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BN/activo corriente','BN/activo corriente','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BN/activo no corriente','BN/activo no corriente','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BN/capital','BN/capital','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BN/DFB','BN/DFB','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BN/DFB C/P','BN/DFB C/P','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BN/DFB L/P','BN/DFB L/P','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BN/FFPP','BN/FFPP','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('BN/ventas','BN/ventas','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('calidad deuda','Calidad Deuda','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('capital/BAI','Capital/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('capital/BAII','Capital/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('capital/BN','Capital/BN','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('capital/cashflow','Capital/cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('capital/EBITDA','Capital/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('capital/ventas','Capital/Ventas','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('cashflow','Cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('cashflow/activo','cashflow/activo','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('cashflow/activo corriente','cashflow/activo corriente','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('cashflow/activo no corriente','cashflow/activo no corriente','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('cashflow/capital','cashflow/capital','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('cashflow/DFB','cashflow/DFB','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('cashflow/DFB C/P','cashflow/DFB C/P','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('cashflow/DFB L/P','cashflow/DFB L/P','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('cashflow/DFN','cashflow/DFN','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('cashflow/FFPP','cashflow/FFPP','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('cashflow/ventas','Cashflow/Ventas','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('compras medias diarias','Compras Medias Diarias','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('coste de deuda','Coste de Deuda','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB','DFB','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB C/P','DFB C/P','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB C/P/BAI','DFB C/P/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB C/P/BAII','DFB C/P/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB C/P/BN','DFB C/P/BN','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB C/P/cashflow','DFB C/P/cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB C/P/EBITDA','DFB C/P/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB C/P/ventas','DFB C/P/ventas','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB L/P','DFB L/P','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB L/P/BAI','DFB L/P/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB L/P/BAII','DFB L/P/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB L/P/BN','DFB L/P/BN','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB L/P/cashflow','DFB L/P/cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB L/P/EBITDA','DFB L/P/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB L/P/ventas','DFB L/P/ventas','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB/BAI','DFB/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB/BAII','DFB/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB/BN','DFB/BN','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB/cashflow','DFB/cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB/EBITDA','DFB/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFB/ventas','DFB/ventas','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFN','DFN','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFN/cashflow','DFN/cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('DFN/EBITDA','DFN/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('disponibilidad','Disponibilidad','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('EBITDA','EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('EBITDA/activo','EBITDA/activo','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('EBITDA/activo corriente','EBITDA/activo corriente','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('EBITDA/activo no corriente','EBITDA/activo no corriente','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('EBITDA/capital','EBITDA/capital','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('EBITDA/DFB','EBITDA/DFB','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('EBITDA/DFB C/P','EBITDA/DFB C/P','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('EBITDA/DFB L/P','EBITDA/DFB L/P','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('EBITDA/FFPP','EBITDA/FFPP','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('EBITDA/ventas','EBITDA/ventas','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('endeudamiento','Endeudamiento','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('FFPP/BAI','FFPP/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('FFPP/BAII','FFPP/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('FFPP/BN','FFPP/BN','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('FFPP/cashflow','FFPP/cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('FFPP/EBITDA','FFPP/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('FFPP/ventas','FFPP/ventas','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('fondo maniobra','Fondo Maniobra','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('fondo maniobra/activo total','Fondo Maniobra/Activo Total','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('liquidez','Liquidez','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('margen de contribucion','Margen de Contribucion','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('PM Cobro','PM Cobro','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('PM Proveedores','PM Proveedores','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('prueba acida','Prueba Ácida','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('punto muerto','Punto Muerto','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('punto muerto mensual','Punto Muerto Mensual','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('ROA/ROI','ROA/ROI','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('ROE','ROE','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('ventas','Ventas','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('ventas medias diarias','Ventas Medias Diarias','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('ventas/activo','Ventas/Activo','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('ventas/activo corriente','Ventas/Activo Corriente','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('ventas/activo no corriente','Ventas/Activo No Corriente','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('ventas/BAI','Ventas/BAI','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('ventas/BAII','Ventas/BAII','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('ventas/BN','Ventas/BN','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('ventas/capital','Ventas/Capital','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('ventas/cashflow','Ventas/Cashflow','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('ventas/DFB','Ventas/DFB','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('ventas/DFB C/P','Ventas/DFB C/P','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('ventas/DFB L/P','Ventas/DFB L/P','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('ventas/EBITDA','Ventas/EBITDA','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('ventas/FFPP','Ventas/FFPP','verde','rojo','arriba','abajo',1)
INSERT INTO RatioMaestros VALUES ('porcentaje cobertura','% Cobertura','verde','rojo','arriba','abajo',2)
INSERT INTO RatioMaestros VALUES ('servicio deuda','Servicio de Deuda','verde','rojo','arriba','abajo',2)
